import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 350
blink_timeout = 0
thickness = 0.25
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2
